export const SET_MODE = 'SET_MODE';
export const SET_TURN_NUMBER = 'SET_TURN_NUMBER';
export const SET_STONE = 'SET_STONE';
export const SET_WINDOW_DIMENSIONS = 'SET_WINDOW_DIMENSIONS';
export const SET_CONFIGURATION_HEIGHT = 'SET_CONFIGURATION_HEIGHT';