export const KO_WARNING = 'KO_WARNING';
export const SET_MODE = 'SET_MODE';
export const SET_LAST_PREVIEW_STONE = 'SET_LAST_PREVIEW_STONE';
export const UPDATE_STONES = 'UPDATE_STONES';
export const SET_WINDOW_DIMENSIONS = 'SET_WINDOW_DIMENSIONS';
export const TOGGLE_CONFIGURATION_PANEL = 'TOGGLE_CONFIGURATION_PANEL';