export const KO_WARNING = 'KO_WARNING';
export const SET_MODE = 'SET_MODE';
export const SET_TURN_NUMBER = 'SET_TURN_NUMBER';
export const UPDATE_STONES = 'UPDATE_STONES';
export const SET_WINDOW_DIMENSIONS = 'SET_WINDOW_DIMENSIONS';